name: Feature Request
description: Propose a new feature or improvement.
title: "[Feature]: "
labels:
  - enhancement
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Share the problem first, then your preferred solution.

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - apps/client
        - apps/api
        - apps/dashboard
        - apps/pilot/host
        - apps/pilot/bridge
        - apps/pilot/server
        - apps/cli
        - packages/daemon
        - packages/computer-use
        - docs
        - other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user/developer problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your preferred approach.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List other options and tradeoffs.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Links, mockups, logs, or references.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues for similar requests.
          required: true
