/**
 * @license
 * Copyright 2025 cofy-x
 * SPDX-License-Identifier: Apache-2.0
 */

import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm'], // Build both CommonJS and ESM versions
  // We don't need to generate .d.ts type files because they are generated by the ../.scripts/build_package.js script
  dts: false, // Automatically generate .d.ts type files
  splitting: false,
  sourcemap: true,
  clean: true, // Clean dist before each build
  minify: false, // Libraries usually don't need compression, leave it to the consumer to compress
  treeshake: true,
});
