/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Deck API
 * The AI Code Infrastructure API
 * OpenAPI spec version: 1.0
 */

export interface CreateExampleDto {
  /**
   * Test Message
   * @minLength 1
   */
  message: string;
}
