/*
Deck Daemon API

Deck Daemon API

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package daemon

import (
	"encoding/json"
)

// checks if the BrowserOpenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrowserOpenRequest{}

// BrowserOpenRequest struct for BrowserOpenRequest
type BrowserOpenRequest struct {
	// Whether to use incognito mode
	Incognito *bool `json:"incognito,omitempty"`
	// Whether to open the 9222 debug port
	RemoteDebug *bool `json:"remoteDebug,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewBrowserOpenRequest instantiates a new BrowserOpenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrowserOpenRequest() *BrowserOpenRequest {
	this := BrowserOpenRequest{}
	return &this
}

// NewBrowserOpenRequestWithDefaults instantiates a new BrowserOpenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrowserOpenRequestWithDefaults() *BrowserOpenRequest {
	this := BrowserOpenRequest{}
	return &this
}

// GetIncognito returns the Incognito field value if set, zero value otherwise.
func (o *BrowserOpenRequest) GetIncognito() bool {
	if o == nil || IsNil(o.Incognito) {
		var ret bool
		return ret
	}
	return *o.Incognito
}

// GetIncognitoOk returns a tuple with the Incognito field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrowserOpenRequest) GetIncognitoOk() (*bool, bool) {
	if o == nil || IsNil(o.Incognito) {
		return nil, false
	}
	return o.Incognito, true
}

// HasIncognito returns a boolean if a field has been set.
func (o *BrowserOpenRequest) HasIncognito() bool {
	if o != nil && !IsNil(o.Incognito) {
		return true
	}

	return false
}

// SetIncognito gets a reference to the given bool and assigns it to the Incognito field.
func (o *BrowserOpenRequest) SetIncognito(v bool) {
	o.Incognito = &v
}

// GetRemoteDebug returns the RemoteDebug field value if set, zero value otherwise.
func (o *BrowserOpenRequest) GetRemoteDebug() bool {
	if o == nil || IsNil(o.RemoteDebug) {
		var ret bool
		return ret
	}
	return *o.RemoteDebug
}

// GetRemoteDebugOk returns a tuple with the RemoteDebug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrowserOpenRequest) GetRemoteDebugOk() (*bool, bool) {
	if o == nil || IsNil(o.RemoteDebug) {
		return nil, false
	}
	return o.RemoteDebug, true
}

// HasRemoteDebug returns a boolean if a field has been set.
func (o *BrowserOpenRequest) HasRemoteDebug() bool {
	if o != nil && !IsNil(o.RemoteDebug) {
		return true
	}

	return false
}

// SetRemoteDebug gets a reference to the given bool and assigns it to the RemoteDebug field.
func (o *BrowserOpenRequest) SetRemoteDebug(v bool) {
	o.RemoteDebug = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BrowserOpenRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrowserOpenRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BrowserOpenRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BrowserOpenRequest) SetUrl(v string) {
	o.Url = &v
}

func (o BrowserOpenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrowserOpenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Incognito) {
		toSerialize["incognito"] = o.Incognito
	}
	if !IsNil(o.RemoteDebug) {
		toSerialize["remoteDebug"] = o.RemoteDebug
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableBrowserOpenRequest struct {
	value *BrowserOpenRequest
	isSet bool
}

func (v NullableBrowserOpenRequest) Get() *BrowserOpenRequest {
	return v.value
}

func (v *NullableBrowserOpenRequest) Set(val *BrowserOpenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBrowserOpenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBrowserOpenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrowserOpenRequest(val *BrowserOpenRequest) *NullableBrowserOpenRequest {
	return &NullableBrowserOpenRequest{value: val, isSet: true}
}

func (v NullableBrowserOpenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrowserOpenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


