/*
Deck Daemon API

Deck Daemon API

API version: v0.0.0-dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package daemon

import (
	"encoding/json"
)

// checks if the PtyCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PtyCreateResponse{}

// PtyCreateResponse struct for PtyCreateResponse
type PtyCreateResponse struct {
	SessionId *string `json:"sessionId,omitempty"`
}

// NewPtyCreateResponse instantiates a new PtyCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPtyCreateResponse() *PtyCreateResponse {
	this := PtyCreateResponse{}
	return &this
}

// NewPtyCreateResponseWithDefaults instantiates a new PtyCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPtyCreateResponseWithDefaults() *PtyCreateResponse {
	this := PtyCreateResponse{}
	return &this
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *PtyCreateResponse) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PtyCreateResponse) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *PtyCreateResponse) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *PtyCreateResponse) SetSessionId(v string) {
	o.SessionId = &v
}

func (o PtyCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PtyCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	return toSerialize, nil
}

type NullablePtyCreateResponse struct {
	value *PtyCreateResponse
	isSet bool
}

func (v NullablePtyCreateResponse) Get() *PtyCreateResponse {
	return v.value
}

func (v *NullablePtyCreateResponse) Set(val *PtyCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePtyCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePtyCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePtyCreateResponse(val *PtyCreateResponse) *NullablePtyCreateResponse {
	return &NullablePtyCreateResponse{value: val, isSet: true}
}

func (v NullablePtyCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePtyCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


