/**
 * @license
 * Copyright 2026 cofy-x
 * SPDX-License-Identifier: Apache-2.0
 */

import type { Config } from '../types/index.js';

export function createAdapterTestConfig(overrides: Partial<Config> = {}): Config {
  return {
    configPath: '/tmp/bridge.config.json',
    configFile: { version: 1 },
    opencodeUrl: 'http://localhost:4096',
    opencodeDirectory: '/tmp',
    opencodeUsername: undefined,
    opencodePassword: undefined,
    model: undefined,
    telegramToken: 'token',
    telegramEnabled: true,
    slackBotToken: 'xoxb-test',
    slackAppToken: 'xapp-test',
    slackEnabled: true,
    feishuWebhookUrl: 'https://example.com/feishu',
    feishuVerificationToken: undefined,
    feishuEventPort: 3011,
    feishuEventPath: '/events/feishu',
    feishuEnabled: true,
    discordToken: 'discord-token',
    discordMentionInGuilds: true,
    discordGatewayProxyUrl: undefined,
    discordGatewayHandshakeTimeoutMs: undefined,
    discordEnabled: true,
    dingtalkWebhookUrl: 'https://example.com/dingtalk',
    dingtalkVerificationToken: undefined,
    dingtalkEventPort: 3012,
    dingtalkEventPath: '/events/dingtalk',
    dingtalkEnabled: true,
    emailEnabled: true,
    emailImapHost: 'imap.example.com',
    emailImapPort: 993,
    emailImapSecure: true,
    emailImapUser: 'user@example.com',
    emailImapPassword: 'secret',
    emailImapMailbox: 'INBOX',
    emailPollIntervalSeconds: 30,
    emailSmtpHost: 'smtp.example.com',
    emailSmtpPort: 587,
    emailSmtpSecure: false,
    emailSmtpUser: 'user@example.com',
    emailSmtpPassword: 'secret',
    emailFromAddress: 'bot@example.com',
    emailSubjectPrefix: 'Re: ',
    emailAutoReplyEnabled: true,
    mochatEnabled: true,
    mochatBaseUrl: 'https://mochat.io',
    mochatClawToken: 'claw_xxx',
    mochatSessions: ['session_1'],
    mochatPollIntervalMs: 30_000,
    mochatWatchTimeoutMs: 25_000,
    mochatWatchLimit: 100,
    qqEnabled: true,
    qqApiBaseUrl: 'http://127.0.0.1:5700',
    qqAccessToken: undefined,
    qqWebhookPort: 3013,
    qqWebhookPath: '/events/qq',
    channelAccessPolicy: {
      telegram: 'open',
      whatsapp: 'open',
      slack: 'open',
      feishu: 'open',
      discord: 'open',
      dingtalk: 'open',
      email: 'open',
      mochat: 'open',
      qq: 'open',
    },
    whatsappAuthDir: '/tmp/wa',
    whatsappAccountId: 'default',
    whatsappAllowFrom: new Set<string>(),
    whatsappSelfChatMode: false,
    whatsappEnabled: true,
    dataDir: '/tmp',
    dbPath: '/tmp/bridge.sqlite',
    logFile: '/tmp/bridge.log',
    allowlist: {
      telegram: new Set<string>(),
      whatsapp: new Set<string>(),
      slack: new Set<string>(),
      feishu: new Set<string>(),
      discord: new Set<string>(),
      dingtalk: new Set<string>(),
      email: new Set<string>(),
      mochat: new Set<string>(),
      qq: new Set<string>(),
    },
    toolUpdatesEnabled: false,
    groupsEnabled: false,
    permissionMode: 'allow',
    toolOutputLimit: 1200,
    healthPort: 3005,
    logLevel: 'info',
    telegramThinkingMode: 'off',
    ...overrides,
  };
}
